services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_coffeeshop
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_DATABASE: coffeeshop
      MONGO_INITDB_ROOT_USERNAME: atul13062001
      MONGO_INITDB_ROOT_PASSWORD: 12345
    # volumes:
    #   - mongo_data:/data/db
    
# volumes:
#   mongo_data: